# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libarchive-dev
  
after_success:
  - Rscript -e 'covr::codecov()'
