context("seaice data sources")

test_that("source nsidc0051 still works under ftp (due to be moved to https)",{
    skip_on_cran()
    temp_root <- tempdir()
    cf <- bb_config(local_file_root=temp_root)
    tmp <- sources(name="NSIDC SMMR-SSM/I Nasateam sea ice concentration")
    tmp$source_url[[1]] <- "ftp://sidads.colorado.edu/pub/DATASETS/nsidc0051_gsfc_nasateam_seaice/final-gsfc/south/daily/1978/nt_19781231_n07_v1.1_s.bin"
    cf <- bb_add(cf,tmp)
    bb_sync(cf,confirm_downloads_larger_than=-1)
    fnm <- file.path(temp_root,"sidads.colorado.edu/pub/DATASETS/nsidc0051_gsfc_nasateam_seaice/final-gsfc/south/daily/1978/nt_19781231_n07_v1.1_s.bin")
    expect_true(file.exists(fnm))
    fi <- file.info(fnm)
    expect_gt(fi$size,50e3)
})

test_that("source nsidc0081 still works under ftp (due to be moved to https)",{
    skip_on_cran()
    temp_root <- tempdir()
    target_file <- format(Sys.Date()-10,"nt_%Y%m%d_f18_nrt_s.bin")
    cf <- bb_config(local_file_root=temp_root)
    tmp <- sources(name="NSIDC SMMR-SSM/I Nasateam near-real-time sea ice concentration")
    tmp$source_url[[1]] <- paste0("ftp://sidads.colorado.edu/pub/DATASETS/nsidc0081_nrt_nasateam_seaice/south/",target_file)
    cf <- bb_add(cf,tmp)
    bb_sync(cf,confirm_downloads_larger_than=-1)
    fnm <- file.path(temp_root,"sidads.colorado.edu/pub/DATASETS/nsidc0081_nrt_nasateam_seaice/south",target_file)
    expect_true(file.exists(fnm))
    fi <- file.info(fnm)
    expect_gt(fi$size,50e3)
})

test_that("seaice AMSR format options work",{
    src <- sources_seaice("AMSR-E_ASI_s6250")
    expect_equal(nrow(src),1)
    expect_true(grepl("/hdf/",src$source_url[[1]],fixed=TRUE))
    expect_error(sources_seaice("AMSR-E_ASI_s6250",formats="bananas"))
    src <- sources_seaice("AMSR-E_ASI_s6250",formats="geotiff")
    expect_equal(nrow(src),1)
    expect_true(grepl("/geotiff/",src$source_url[[1]],fixed=TRUE))
    expect_false(grepl("/hdf/",src$source_url[[1]],fixed=TRUE))
    src <- sources_seaice("AMSR-E_ASI_s6250",formats=c("hdf","geotiff"))
    expect_equal(nrow(src),1)
    expect_equal(length(src$source_url[[1]]),2)
    expect_true(any(grepl("/geotiff/",src$source_url[[1]],fixed=TRUE)))
    expect_true(any(grepl("/hdf/",src$source_url[[1]],fixed=TRUE)))
})
